# Generated by Django 2.2.5 on 2019-12-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinishStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Width', models.IntegerField(null=True)),
                ('Height', models.IntegerField(null=True)),
                ('Distance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Code', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
                ('LastCoordX', models.IntegerField(null=True)),
                ('LastCoordY', models.IntegerField(null=True)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='RobotActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Producer', models.CharField(max_length=250)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StartStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('EnterPosX', models.IntegerField()),
                ('EnterPosY', models.IntegerField()),
                ('ExitPosX', models.IntegerField()),
                ('ExitPosY', models.IntegerField()),
                ('SecondPerMeter', models.IntegerField(null=True)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='TransferVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('LastPosX', models.IntegerField(null=True)),
                ('LastPosY', models.IntegerField(null=True)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='TransferredObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=False)),
                ('LastPosX', models.IntegerField(null=True)),
                ('LastPosY', models.IntegerField(null=True)),
                ('Length', models.IntegerField(null=True)),
                ('isNewObject', models.BooleanField(default=False)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
                ('StartStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StartStation_TO', to='robots.StartStation')),
                ('TransferVehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransferVehicle_TO', to='robots.TransferVehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TObjectWaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('EnfDateTime', models.DateTimeField()),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
                ('TransferredObjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.TransferredObjects')),
                ('WaitingStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.WaitingStation')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrder', models.IntegerField(null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('FinishStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FinishStation_TOTask', to='robots.FinishStation')),
                ('Robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Robot_TOTask', to='robots.Robot')),
                ('TransferVehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransferVehicle_TOTask', to='robots.TransferVehicle')),
                ('TransferredObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.TransferredObjects')),
                ('WaitingStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='WaitingStation_TOTask', to='robots.WaitingStation')),
                ('WorkStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='WorkStation_TOTask', to='robots.WorkStation')),
            ],
        ),
        migrations.CreateModel(
            name='SubNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('UniqueCode', models.CharField(max_length=500)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='RobotLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionX', models.FloatField()),
                ('PositionY', models.FloatField()),
                ('RobotActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotActivity')),
                ('Sticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Sticker')),
            ],
        ),
        migrations.CreateModel(
            name='RobotCharging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('EnfDateTime', models.DateTimeField()),
                ('ChargingStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.ChargingStation')),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
                ('Robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Robot')),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='RobotModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotModel'),
        ),
        migrations.CreateModel(
            name='ObstaclePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Left', models.IntegerField()),
                ('Right', models.IntegerField()),
                ('Top', models.IntegerField()),
                ('Bottom', models.IntegerField()),
                ('CenterX', models.IntegerField()),
                ('CenterY', models.IntegerField()),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentSticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_sticker', to='robots.Sticker')),
                ('Down', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='down_sticker', to='robots.Sticker')),
                ('Left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_sticker', to='robots.Sticker')),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
                ('Right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_sticker', to='robots.Sticker')),
                ('Top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_sticker', to='robots.Sticker')),
            ],
        ),
        migrations.CreateModel(
            name='MapGoalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50)),
                ('Left', models.IntegerField()),
                ('Right', models.IntegerField()),
                ('Top', models.IntegerField()),
                ('Bottom', models.IntegerField()),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='SubNet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.SubNet'),
        ),
        migrations.AddField(
            model_name='finishstation',
            name='Map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='Map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map'),
        ),
    ]
