# Generated by Django 2.1.2 on 2018-11-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Producer', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='RobotModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotModel'),
        ),
    ]
