# Generated by Django 2.1.3 on 2019-12-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='Map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='isMoving',
            field=models.BooleanField(default=False),
        ),
    ]
