# Generated by Django 2.1.2 on 2018-11-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RobotActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='RobotLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionX', models.FloatField()),
                ('PositionY', models.FloatField()),
                ('RobotActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotActivity')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('UniqueCode', models.CharField(max_length=500)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='SubNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='subnet',
            name='Tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Tenant'),
        ),
        migrations.AddField(
            model_name='robotlocation',
            name='Sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Sticker'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='Down',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='down_sticker', to='robots.Sticker'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='Left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_sticker', to='robots.Sticker'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='Map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='Right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_sticker', to='robots.Sticker'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='Top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_sticker', to='robots.Sticker'),
        ),
        migrations.AddField(
            model_name='map',
            name='SubNet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.SubNet'),
        ),
    ]
