# Generated by Django 2.1.3 on 2019-12-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20191206_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferredobjects',
            name='isNewObject',
        ),
    ]
