# Generated by Django 2.1.2 on 2018-11-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20181113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='SubNet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.SubNet'),
        ),
        migrations.AddField(
            model_name='robot',
            name='Tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Tenant'),
        ),
    ]
