# Generated by Django 2.1.3 on 2019-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_remove_transferredobjects_isnewobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='isCurrentJob',
            field=models.BooleanField(default=False),
        ),
    ]
