# Generated by Django 2.1.2 on 2018-11-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20181113_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='RobotModel',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='SubNet',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='Tenant',
        ),
        migrations.RemoveField(
            model_name='robotactivity',
            name='Robot',
        ),
        migrations.RemoveField(
            model_name='robotlocation',
            name='RobotActivity',
        ),
        migrations.RemoveField(
            model_name='robotlocation',
            name='Sticker',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
        migrations.DeleteModel(
            name='RobotActivity',
        ),
        migrations.DeleteModel(
            name='RobotLocation',
        ),
    ]
