# Generated by Django 2.2.5 on 2019-12-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_taskhistory_iscurrentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='WorkTimeEndPoint',
            field=models.IntegerField(null=True),
        ),
    ]
