# Generated by Django 2.1.2 on 2018-11-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_auto_20181113_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Code', models.CharField(max_length=50)),
                ('RobotModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotModel')),
                ('SubNet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.SubNet')),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RobotActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='RobotLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionX', models.FloatField()),
                ('PositionY', models.FloatField()),
                ('RobotActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotActivity')),
                ('Sticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Sticker')),
            ],
        ),
    ]
