# Generated by Django 2.2.5 on 2019-12-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_taskhistory_worktimeendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='isCompleted',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='isCurrentJob',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='isMoving',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='TaskType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.TaskType'),
        ),
    ]
