# Generated by Django 2.1.2 on 2018-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robot_robotactivity_robotlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmodel',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
