# Generated by Django 2.2.5 on 2019-12-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_auto_20191212_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='TaskType',
            field=models.CharField(default='001', max_length=3),
        ),
    ]
