# Generated by Django 2.1.3 on 2018-11-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_robotmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='Down',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='Left',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='Map',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='Right',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='Top',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
