# Generated by Django 2.2.5 on 2019-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0007_auto_20191212_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='TaskType',
            field=models.IntegerField(null=True),
        ),
    ]
