# Generated by Django 2.2.5 on 2019-12-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0009_taskhistory_startstation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tobjectwaiting',
            old_name='TransferredObjects',
            new_name='TransferredObject',
        ),
    ]
