# Generated by Django 2.1.3 on 2018-11-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0009_auto_20181126_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='Down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='down_sticker', to='robots.Sticker'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='Left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_sticker', to='robots.Sticker'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='Right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_sticker', to='robots.Sticker'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='Top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_sticker', to='robots.Sticker'),
        ),
    ]
