# Generated by Django 2.2.5 on 2019-12-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0011_auto_20191212_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferredObjects',
            new_name='TransferredObject',
        ),
    ]
