# Generated by Django 2.1.3 on 2019-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0011_auto_20190823_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstationsection',
            name='ChargingStation',
        ),
        migrations.RemoveField(
            model_name='chargingstationsection',
            name='Robot',
        ),
        migrations.RemoveField(
            model_name='waitingstationsection',
            name='Map',
        ),
        migrations.RemoveField(
            model_name='waitingstationsection',
            name='TransferredObjects',
        ),
        migrations.RemoveField(
            model_name='waitingstationsection',
            name='WaitingStation',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='Position',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitingstation',
            name='Position',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='waitingstation',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChargingStationSection',
        ),
        migrations.DeleteModel(
            name='WaitingStationSection',
        ),
    ]
