# Generated by Django 2.2.5 on 2019-12-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0012_auto_20191212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='TransferredObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.TransferredObject'),
        ),
        migrations.AddField(
            model_name='tobjectwaiting',
            name='TransferredObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.TransferredObject'),
        ),
    ]
