# Generated by Django 2.2.5 on 2019-12-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0013_auto_20191212_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfervehicle',
            old_name='isFull',
            new_name='isBusy',
        ),
    ]
