# Generated by Django 2.1.3 on 2019-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0013_robotcharging_tobjectwaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='CenterX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='CenterY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitingstation',
            name='CenterX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitingstation',
            name='CenterY',
            field=models.IntegerField(default=0),
        ),
    ]
