# Generated by Django 2.2.5 on 2019-12-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0014_auto_20191212_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='TaskType',
            new_name='TaskStatus',
        ),
    ]
