# Generated by Django 2.1.3 on 2019-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0014_auto_20190902_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='EnterPosX',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='EnterPosY',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='ExitPosX',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='ExitPosY',
            field=models.IntegerField(),
        ),
    ]
