# Generated by Django 2.2.4 on 2019-10-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_auto_20190905_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferredobjectstask',
            name='Code',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='WaitingStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='WaitingStation_TOTask', to='robots.WaitingStation'),
        ),
        migrations.AddField(
            model_name='transferredobjectstask',
            name='Order',
            field=models.IntegerField(null=True),
        ),
    ]
