# Generated by Django 2.2.5 on 2019-12-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_auto_20191212_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='isBusy',
            field=models.BooleanField(default=False),
        ),
    ]
