# Generated by Django 2.2.4 on 2019-10-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0016_auto_20191008_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borcode', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=False)),
                ('LastPosX', models.IntegerField(null=True)),
                ('LastPosY', models.IntegerField(null=True)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='StartStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.CreateModel(
            name='FinishStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('isFull', models.BooleanField(default=False)),
                ('Position', models.CharField(blank=True, max_length=2000)),
                ('CenterX', models.IntegerField(default=0)),
                ('CenterY', models.IntegerField(default=0)),
                ('Map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.Map')),
            ],
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='EndStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FinishStation_TOTask', to='robots.FinishStation'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='TransferVehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransferVehicle_TOTask', to='robots.TransferVehicle'),
        ),
        migrations.AddField(
            model_name='transferredobjects',
            name='StartStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StartStation_TO', to='robots.StartStation'),
        ),
        migrations.AddField(
            model_name='transferredobjects',
            name='TransferVehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransferVehicle_TO', to='robots.TransferVehicle'),
        ),
    ]
