# Generated by Django 2.2.4 on 2019-12-17 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0016_robot_isbusy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RobotStatus', models.IntegerField(default=1)),
                ('Robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Robot')),
                ('TaskHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TaskHistory_RobotTaskHistory', to='robots.TaskHistory')),
            ],
        ),
        migrations.AddField(
            model_name='transferredobject',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 16, 20, 151513)),
        ),
        migrations.CreateModel(
            name='RobotTaskHistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RobotStatus', models.IntegerField(default=1)),
                ('LogTime', models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 16, 20, 154509))),
                ('RobotTaskHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotTaskHistory')),
            ],
        ),
    ]
