# Generated by Django 2.2.4 on 2019-10-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0017_auto_20191008_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='EndStation',
            new_name='FinishStation',
        ),
    ]
