# Generated by Django 2.2.4 on 2019-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0018_auto_20191008_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfervehicle',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
    ]
