# Generated by Django 2.2.4 on 2019-12-17 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0018_auto_20191217_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotlocation',
            name='RobotActivity',
        ),
        migrations.AddField(
            model_name='robotlocation',
            name='LocationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 38, 39, 741992)),
        ),
        migrations.AddField(
            model_name='robotlocation',
            name='Robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robotlocation_robot', to='robots.Robot'),
        ),
        migrations.AlterField(
            model_name='robottaskhistorylog',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 38, 39, 747971)),
        ),
        migrations.AlterField(
            model_name='transferredobject',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 38, 39, 744975)),
        ),
        migrations.DeleteModel(
            name='RobotActivity',
        ),
    ]
