# Generated by Django 2.2.4 on 2019-12-17 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0019_auto_20191217_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlocation',
            name='LocationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 39, 8, 194865)),
        ),
        migrations.AlterField(
            model_name='robottaskhistorylog',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 39, 8, 201846)),
        ),
        migrations.AlterField(
            model_name='transferredobject',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 9, 39, 8, 197901)),
        ),
    ]
