# Generated by Django 2.2.4 on 2019-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0019_transfervehicle_isfull'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferredobjects',
            old_name='Borcode',
            new_name='Barcode',
        ),
        migrations.RenameField(
            model_name='transfervehicle',
            old_name='Borcode',
            new_name='Barcode',
        ),
    ]
