# Generated by Django 2.2.4 on 2019-10-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0020_auto_20191008_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='TransferredObjectsTask',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='TransferredObject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='robots.TransferredObjects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TransferredObjectsTask',
        ),
    ]
