# Generated by Django 2.2.4 on 2019-12-17 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0020_auto_20191217_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlocation',
            name='LocationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 24, 956341)),
        ),
        migrations.AlterField(
            model_name='robottaskhistory',
            name='TaskHistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaskHistory_RobotTaskHistory', to='robots.TaskHistory'),
        ),
        migrations.AlterField(
            model_name='robottaskhistorylog',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 24, 962326)),
        ),
        migrations.AlterField(
            model_name='transferredobject',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 24, 959301)),
        ),
    ]
