# Generated by Django 2.2.4 on 2019-12-17 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0021_auto_20191217_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlocation',
            name='LocationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 43, 609637)),
        ),
        migrations.AlterField(
            model_name='robottaskhistorylog',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 43, 615621)),
        ),
        migrations.AlterField(
            model_name='transferredobject',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 38, 43, 611600)),
        ),
    ]
