# Generated by Django 2.2.4 on 2019-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0023_auto_20191217_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='WorkTime',
            field=models.DateTimeField(null=True),
        ),
    ]
