# Generated by Django 2.2.4 on 2019-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0024_taskhistory_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='isExitTask',
            field=models.BooleanField(default=False),
        ),
    ]
