# Generated by Django 2.2 on 2019-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0025_taskhistory_isexittask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='isTaskGoingToVehicle',
            field=models.BooleanField(default=False),
        ),
    ]
