# Generated by Django 2.2 on 2020-02-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0026_taskhistory_istaskgoingtovehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=250)),
                ('PositionX', models.IntegerField()),
                ('PositionY', models.IntegerField()),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.Map')),
            ],
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='Map',
        ),
        migrations.RemoveField(
            model_name='robotlocation',
            name='Sticker',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
